// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0yHg9efSbKHLysDCMlPtkSJSwJ84L8TM',
    appId: '1:889303396455:android:0412bb02489c289287e4c2',
    messagingSenderId: '889303396455',
    projectId: 'calendar-855c4',
    storageBucket: 'calendar-855c4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgBjvJvCkgRIurwoYkJhqniiBrVFneLpU',
    appId: '1:889303396455:ios:67fa00f06e8ce72687e4c2',
    messagingSenderId: '889303396455',
    projectId: 'calendar-855c4',
    storageBucket: 'calendar-855c4.appspot.com',
    androidClientId: '889303396455-dk3hpegiqs76qsltkpah3j21sbepf6q0.apps.googleusercontent.com',
    iosClientId: '889303396455-78cqbtd9r08fcb3mvnrln3edro9a49c0.apps.googleusercontent.com',
    iosBundleId: 'com.example.googleCalendar',
  );
}
